<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);NU1903;NU1902</NoWarn>
    <VersionPrefix>$([System.IO.File]::ReadAllText('$([System.IO.Path]::Combine($(MSBuildProjectDirectory), '..', 'version.txt'))').Trim())</VersionPrefix>
    <Version>$(VersionPrefix)</Version>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <InformationalVersion>$(VersionPrefix)</InformationalVersion>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="app.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.11" />
  </ItemGroup>

</Project>
