plugins {
    id 'com.android.application'
}

android {
    namespace 'com.conan.servermanager'
    compileSdk 34

    signingConfigs {
        release {
            storeFile file('../conan-release.keystore')
            storePassword 'conan123'
            keyAlias 'conan'
            keyPassword 'conan123'
        }
    }

    defaultConfig {
        applicationId "com.conan.servermanager"
        minSdk 24
        targetSdk 34
        versionCode 111
        versionName "1.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ""
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
